### PR TITLE
Add Oksolar Dark Theme

### PR DESCRIPTION
**Pull request by Game-Warrior**
These themes are a variation on Solarized based on a new colorspace called [OKLab](https://bottosson.github.io/posts/oklab/). A description of the themes by the author can be found [in this blog post](https://meat.io/oksolar). As far as I can tell this should be ready to merge but please let me know if if needs any work. Thanks for creating such a great Lemmy app!

Sorry for the duplication I forgot to add the themes to themeOptions.ts

### CODE REVIEW

**Review by sgriff96 — CHANGES_REQUESTED** [review]
Light theme needs some work
CleanShot 2023-06-27 at 00 17 40

**Comment by Game-Warrior** [comment]
Ooh that looks bad. I added the light theme as an afterthought. I will probably delete it for now and work on it when I have more time.

**Comment by Game-Warrior** [comment]
I think I have the light theme figured out. I want to test it first but I am have trouble building locally. The dark theme should be ready to roll though.

**Review by sgriff96 — CHANGES_REQUESTED** [review]
There's some stuff messed up with imports/exports etc. Looks like some existing themes got deleted too.

**Comment by Game-Warrior** [comment]
The options should be correct now.

**Comment by Game-Warrior** [comment]
I tried to run this into a simulator but it tells me "cannnot read property 'textSecondary' of undefined". I am not sure what to do...
simulator_screenshot_5270B9EA-1833-4DE2-99D8-B12BC71C646B

**Review by sgriff96 — APPROVED** [review]
Cleaned it up a bit, fixed errors. Should be okay now.

**Pull request merged**
