### PR TITLE
feat: compact thumbnail position

### PR DESCRIPTION
**Pull request by qoopa**
Adds setting option for setting thumbnail position to right (defailt) or left. 

Helpful for people like me that scroll with left hand and still want to see the thumbnails.

### CODE REVIEW

**Comment by gkasdorf** [comment]
@qoopa Thanks! Do you think it would be better to also move the arrows to the reverse site?

**Comment by gkasdorf** [comment]
Also thank you for cleaning up the component in general and breaking it down 🙏 One less component that I'll need to go back and clean up.

**Comment by qoopa** [comment]
> @qoopa Thanks! Do you think it would be better to also move the arrows to the reverse site?

Not sure, I let them be just because Apollo has them on the same side when the thumbnail is on the Left side. 

Thought about adding the option to hide the vote arrows too (in a other PR) since you can vote with swipe now.

**Comment by gkasdorf** [comment]
Ah, gotcha. I'm fine with it either way. We can go with this PR and see what user feedback is on it.

Let me build real quick and see if everything is cool and I'll merge it in. As for hiding the arrows, either you can do it or I'll add it in with this. Up to you 👍

**Pull request merged**
