### PR TITLE
Create Dracula Theme

### PR DESCRIPTION
**Pull request by daltonlicause**
Hey @gkasdorf, here's my attempt at adding the [Dracula theme](https://draculatheme.com/) to Memmy. First time working with a react native project so let me know if I need to change anything. 

Also wanted to ask if you plan to add the option to change the navigation icon colors.

### CODE REVIEW

**Comment by gkasdorf** [comment]
@daltonlicause Hey thank you! @sgriff96 is working on minimizing the theme template params, so as soon as he is finished I'll just apply this theme to the new variables. I'll update you once it's done and as soon as it is I'll push it into the repo. Really appreciate this!

And yea, we can add that into the theme options.

**Comment by sgriff96** [comment]
Hey Dalton, could you do me a favor and throw up a screenshot of what this looks like if you have one handy? If not I will pull this down and see what it looks like eventually

**Comment by daltonlicause** [comment]
Sounds good @gkasdorf, thank you! 

Hey @sgriff96, yep here are a few screenshots!

Simulator Screen Shot - iPhone 13 - 2023-06-25 at 15 40 52
Simulator Screen Shot - iPhone 13 - 2023-06-25 at 15 41 00
Simulator Screen Shot - iPhone 13 - 2023-06-25 at 15 41 21
Simulator Screen Shot - iPhone 13 - 2023-06-25 at 15 44 10
Simulator Screen Shot - iPhone 13 - 2023-06-25 at 15 46 28

**Comment by sgriff96** [comment]
Thanks @daltonlicause, I just merged #121 that has 2 dracula theme options. Used some of your colors for it so thanks for that!

**Pull request closed without merging**
