### PR TITLE
Added a toggle to fully collapse comments & fixed comment note spacing

### PR DESCRIPTION
**Pull request by ktgd**
- Added a toggle setting to fully collapse comments into just the header.
- Fixed comment note spacing

### CODE REVIEW

**Comment by ktgd** [comment]
Previously, the comment notes (i.e. "Comment collapsed") used the Text and the normal comments used RenderMarkdown. Because of a spacing/margin difference, collapsing a single line comment would cause it to get larger not smaller.

I updated RenderMarkdown to include an isNote boolean prop used as a toggle to match the style of the original comment notes. By using RenderMarkdown for both comments and comment notes, collapsing a single line comment will keep the same spacing.

**Comment by gkasdorf** [comment]
Do you think we necessarily need an option for collapsing them all the way? I think it might be better to just have them collapse into something a *little* bigger (easier for pressing to re-open, and having that as the default. I don't think I've seen anyone who particularly likes the current functionality.

**Comment by ktgd** [comment]
Good point! I definitely like them collapsing more than they were originally. I'll add a spacer in so they are a little bit bigger (and easier to click), make that the default and remove the toggle.

**Comment by ktgd** [comment]
Fixed. Thanks for the tip!

**Comment by gkasdorf** [comment]
Added a down chevron icon to indicate that the comment is collapsed. Otherwise everything was 💯 

Really going to need to go in and clean this component up and break it down, probably will do it tomorrow.

Thanks!

**Pull request merged**
